import { FarmingRange_depositedLpTokens } from "./depositedLpTokens.test";
import { FarmingRange_depositedCoverTokens } from "./depositedCoverTokens.test";
import { FarmingRange_yieldBonusChanged } from "./yieldBonusChanged.test";
import { FarmingRange_deposit } from "./deposit.test";
import { FarmingRange_depositLpNft } from "./depositLpNft.test";
import { FarmingRange_depositCoverNft } from "./depositCoverNft.test";
import { FarmingRange_depositWithPermit } from "./depositWithPermit.test";
import { FarmingRange_withdraw } from "./withdraw.test";
import { FarmingRange_withdrawLpNft } from "./withdrawLpNft.test";
import { FarmingRange_withdrawCoverNft } from "./withdrawCoverNft.test";
import { FarmingRange_harvest } from "./harvest.test";
import { FarmingRange_emergencyWithdraw } from "./emergencyWithdraw.test";
import { FarmingRange_emergencyWithdrawNft } from "./emergencyWithdrawNft.test";
import { FarmingRange_freezeExpiredCoverRewards } from "./freezeExpiredCoverRewards.test";
import { FarmingRange_forceExpiredCoverWithdrawal } from "./forceExpiredCoverWithdrawal.test";
import { FarmingRange_forceExpiredCoverWithdrawalMultiple } from "./forceExpiredCoverWithdrawalMultiple.test";
import { FarmingRange_setRewardInfoLimit } from "./setRewardInfoLimit.test";
import { FarmingRange_addCampaignInfo } from "./addCampaignInfo.test";
import { FarmingRange_addRewardInfo } from "./addRewardInfo.test";
import { FarmingRange_addRewardInfoMultiple } from "./addRewardInfoMultiple.test";
import { FarmingRange_updateRewardInfo } from "./updateRewardInfo.test";
import { FarmingRange_updateRewardMultiple } from "./updateRewardMultiple.test";
import { FarmingRange_updateCampaignsRewards } from "./updateCampaignsRewards.test";
import { FarmingRange_removeLastRewardInfo } from "./removeLastRewardInfo.test";
import { FarmingRange_rewardInfoLen } from "./rewardInfoLen.test";
import { FarmingRange_campaignInfoLen } from "./campaignInfoLen.test";
import { FarmingRange_currentEndBlock } from "./currentEndBlock.test";
import { FarmingRange_currentRewardPerBlock } from "./currentRewardPerBlock.test";
import { FarmingRange_getMultiplier } from "./getMultiplier.test";
import { FarmingRange_pendingReward } from "./pendingReward.test";
import { FarmingRange_updateCampaign } from "./updateCampaign.test";
import { FarmingRange_massUpdateCampaigns } from "./massUpdateCampaigns.test";
import { FarmingRange_attemptTransfer } from "./attemptTransfer.test";
import { FarmingRange_setStaking } from "./setStaking.test";

export function FarmingRangeTests() {
  FarmingRange_depositedLpTokens();
  FarmingRange_depositedCoverTokens();
  FarmingRange_yieldBonusChanged();
  FarmingRange_deposit();
  FarmingRange_depositLpNft();
  FarmingRange_depositCoverNft();
  FarmingRange_depositWithPermit();
  FarmingRange_withdraw();
  FarmingRange_withdrawLpNft();
  FarmingRange_withdrawCoverNft();
  FarmingRange_harvest();
  FarmingRange_emergencyWithdraw();
  FarmingRange_emergencyWithdrawNft();
  FarmingRange_freezeExpiredCoverRewards();
  FarmingRange_forceExpiredCoverWithdrawal();
  FarmingRange_forceExpiredCoverWithdrawalMultiple();
  FarmingRange_setRewardInfoLimit();
  FarmingRange_addCampaignInfo();
  FarmingRange_addRewardInfo();
  FarmingRange_addRewardInfoMultiple();
  FarmingRange_updateRewardInfo();
  FarmingRange_updateRewardMultiple();
  FarmingRange_updateCampaignsRewards();
  FarmingRange_removeLastRewardInfo();
  FarmingRange_rewardInfoLen();
  FarmingRange_campaignInfoLen();
  FarmingRange_currentEndBlock();
  FarmingRange_currentRewardPerBlock();
  FarmingRange_getMultiplier();
  FarmingRange_pendingReward();
  FarmingRange_updateCampaign();
  FarmingRange_massUpdateCampaigns();
  FarmingRange_attemptTransfer();
  FarmingRange_setStaking();
}
